/**
 * @typedef {{ risposta: string, sillabe: string }} Parola
 */

/** @param {[string, string][]} elenco */
function conSillabe(elenco) {
  return elenco.map(([risposta, sillabe]) => ({ risposta, sillabe }));
}

const IT = [
  ['finestra', 'fi-ne-stra'],
  ['quaderno', 'qua-der-no'],
  ['bambino', 'bam-bi-no'],
  ['colazione', 'co-la-zio-ne'],
  ['famiglia', 'fa-mi-glia'],
  ['mattina', 'mat-ti-na'],
  ['stazione', 'sta-zio-ne'],
  ['giardino', 'giar-di-no'],
  ['bicicletta', 'bi-ci-clet-ta'],
  ['cioccolato', 'cioc-co-la-to'],
  ['farfalla', 'far-fal-la'],
  ['montagna', 'mon-ta-gna'],
  ['ombrello', 'om-brel-lo'],
  ['cucchiaio', 'cuc-chia-io'],
  ['tovaglia', 'to-va-glia'],
  ['cappello', 'cap-pel-lo'],
  ['ospedale', 'o-spe-da-le'],
  ['biblioteca', 'bi-blio-te-ca'],
  ['formaggio', 'for-mag-gio'],
  ['pomodoro', 'po-mo-do-ro'],
  ['casa', 'ca-sa'],
  ['arancia', 'a-ran-cia'],
  ['fragola', 'fra-go-la'],
  ['pane', 'pa-ne'],
  ['biscotto', 'bi-scot-to'],
  ['sole', 'so-le'],
  ['maestra', 'ma-e-stra'],
  ['dottore', 'dot-to-re'],
  ['cuscino', 'cu-sci-no'],
  ['luna', 'lu-na'],
  ['cane', 'ca-ne'],
  ['mare', 'ma-re'],
  ['mela', 'me-la'],
  ['nido', 'ni-do'],
  ['mercato', 'mer-ca-to'],
  ['gatto', 'gat-to'],
  ['pantalone', 'pan-ta-lo-ne'],
  ['uccello', 'uc-cel-lo'],
  ['libro', 'li-bro'],
  ['palla', 'pal-la'],
  ['pioggia', 'piog-gia'],
  ['treno', 'tre-no'],
  ['fiore', 'fio-re'],
  ['latte', 'lat-te'],
  ['mamma', 'mam-ma'],
  ['bottiglia', 'bot-ti-glia'],
  ['forchetta', 'for-chet-ta'],
  ['lavagna', 'la-va-gna'],
  ['porta', 'por-ta'],
  ['macchina', 'mac-chi-na'],
];

const EN = [
  ['apple', 'ap-ple'],
  ['water', 'wa-ter'],
  ['mother', 'moth-er'],
  ['father', 'fa-ther'],
  ['table', 'ta-ble'],
  ['brother', 'broth-er'],
  ['tiger', 'ti-ger'],
  ['river', 'ri-ver'],
  ['paper', 'pa-per'],
  ['puppy', 'pup-py'],
  ['candy', 'can-dy'],
  ['lemon', 'lem-on'],
  ['pizza', 'piz-za'],
  ['music', 'mu-sic'],
  ['robot', 'ro-bot'],
  ['honey', 'hon-ey'],
  ['morning', 'mor-ning'],
  ['evening', 'eve-ning'],
  ['fairy', 'fai-ry'],
  ['pony', 'po-ny'],
  ['family', 'fam-i-ly'],
  ['people', 'peo-ple'],
  ['children', 'chil-dren'],
  ['teacher', 'teach-er'],
  ['animal', 'an-i-mal'],
  ['elephant', 'el-e-phant'],
  ['butterfly', 'but-ter-fly'],
  ['rainbow', 'rain-bow'],
  ['sunshine', 'sun-shine'],
  ['holiday', 'hol-i-day'],
  ['birthday', 'birth-day'],
  ['present', 'pres-ent'],
  ['baby', 'ba-by'],
  ['jacket', 'jack-et'],
  ['basket', 'bas-ket'],
  ['rocket', 'rock-et'],
  ['planet', 'plan-et'],
  ['mountain', 'moun-tain'],
  ['kitchen', 'kit-chen'],
  ['bedroom', 'bed-room'],
  ['breakfast', 'break-fast'],
  ['sandwich', 'sand-wich'],
  ['chocolate', 'choc-o-late'],
  ['umbrella', 'um-brel-la'],
  ['giraffe', 'gi-raffe'],
  ['penguin', 'pen-guin'],
  ['dolphin', 'dol-phin'],
  ['village', 'vil-lage'],
  ['treasure', 'trea-sure'],
  ['castle', 'cas-tle'],
];

/** @type {Parola[]} */
export const PAROLE_IT = conSillabe(IT);
/** @type {Parola[]} */
export const PAROLE_EN = conSillabe(EN);
